export const START_SEARCH = "START_SEARCH"
export const LOAD_ALBUM = "LOAD_ALBUM"
export const STOP_SEARCH = "STOP_SEARCH"
export const UNLOAD_ALBUM = "UNLOAD_ALBUM"
export const CLEAR_ALBUM = "CLEAR_ALBUM"

export const SET_TRACK = "SET_TRACK"
export const SET_DEVICE_ID = "SET_DEVICE_ID"

export const UPDATE_FIELD = "UPDATE_FIELD"
export const SEARCH_ENTERED = "SEARCH_ENTERED"
export const SET_SEARCH_RESULT = "SET_SEARCH_RESULT"

export const INSERT_ALBUM_CACHE = "INSERT_ALBUM_CACHE"
export const INSERT_SEARCH_CACHE = "INSERT_SEARCH_CACHE"
export const INSERT_TRACK_CACHE = "INSERT_TRACK_CACHE"
export const SET_TOKEN = "SET_TOKEN"

export const INSERT_SEARCHED_ALBUM = "INSERT_SEARCHED_ALBUM"
export const INSERT_CLICKED_ALBUM = "INSERT_CLICKED_ALBUM"